### ISSUE TITLE
Greek letters cause '(invalid character)' error

### ISSUE THREAD

**Issue by sandrolovnicki** [sandrolovnicki/pLam#7]
On some systems, Greek letters α,β,λ in pLam's output cause a crash with
`<stdout>: commitBuffer: invalid argument (invalid character)`

**Comment by pedrofurla** [comment]
Can you elaborate on a way to reproduce this? I am willing to help.

**Comment by sandrolovnicki** [comment]
I'm not sure how to reproduce this. I tried changing my encoding and it all run ok, just had strange symbols. 2 people have reported this, you can see some details on reddit comment thread https://www.reddit.com/r/programming/comments/cvalcl/plam_a_mighty_tool_for_learning_and_exploring/ey7rzz4/?context=8&depth=9

It must be something with character encoding on a specific machine or terminal, but I'm not sure. I will probably just make some script to replace Greek characters in source code, for the people who have this problem

**Comment by pedrofurla** [comment]
Thanks for the link. I wonder if it's docker that is causing this. Related https://github.com/Gabriel439/bench/issues/40.

**Comment by pedrofurla** [comment]
Following the reddit post instructions the error also happened on my mac.
